version: '3.9'

networks:
  cinemax_network:
    driver: bridge

services:
  db_server:
    image: mariadb:10.5.9
    restart: always
    container_name: '${APP_NAME}-db'
    volumes:
      - ./schemas:/var/lib/mysql:rw
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - ${DB_PORT}:3306
    networks:
      - cinemax_network

  server:
    build:
      context: ./
      dockerfile: dockerfile
    container_name: '${APP_NAME}-server'
    restart: always
    ports:
      - ${APP_SERVER_PORT}:80
    volumes:
      - .:/var/www/html:rw
    networks:
      - cinemax_network
    links:
      - db_server


volumes:
  schemas: {}
  html: {}
