DROP DATABASE IF EXISTS cinemax;
CREATE DATABASE cinemax;
USE cinemax;


DROP TABLE IF EXISTS USUARIO;
CREATE TABLE USUARIO(
ID_USUARIO INT(11) PRIMARY KEY AUTO_INCREMENT,
NOMBRE_USUARIO VARCHAR(70) NOT NULL,
CLAVE_USUARIO VARCHAR(20) NOT NULL,
TIPO_USUARIO ENUM('Cliente','Administrador') NOT NULL
);

DROP TABLE IF EXISTS ADMINISTRADOR;
CREATE TABLE ADMINISTRADOR(
ID_ADMIN INT(11) PRIMARY KEY AUTO_INCREMENT,
NOMBRE_ADMIN VARCHAR(60) NOT NULL,
APELLIDO_ADMIN VARCHAR(60) NOT NULL,
EMAIL_ADMIN VARCHAR(70) UNIQUE NOT NULL,
CELULAR_ADMIN VARCHAR(10) UNIQUE NOT NULL,
ID_USUARIO INT(11) NOT NULL,
FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
ON UPDATE CASCADE 
ON DELETE RESTRICT
);


DROP TABLE IF EXISTS CLIENTE;
CREATE TABLE CLIENTE(
ID_CLIENTE INT(11) PRIMARY KEY AUTO_INCREMENT,
NOMBRE_CLIENTE VARCHAR(60) NOT NULL,
APELLIDO_CLIENTE VARCHAR(60) NOT NULL,
FECHA_NACIMIENTO_CLIENTE DATE NOT NULL,
EMAIL_CLIENTE VARCHAR(70) NOT NULL UNIQUE,
CELULAR_CLIENTE VARCHAR(10) NOT NULL UNIQUE,
ID_USUARIO INT(11) NOT NULL,
FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
ON UPDATE CASCADE 
ON DELETE RESTRICT
);


DROP TABLE IF EXISTS PELICULA;
CREATE TABLE PELICULA(
ID_PELICULA INT(11) PRIMARY KEY AUTO_INCREMENT,
TITULO_PELICULA VARCHAR(60) NOT NULL,
GENERO VARCHAR(60) NOT NULL,
AÑO_PUBLICACION DATE NOT NULL
);


DROP TABLE IF EXISTS RESERVA;
CREATE TABLE RESERVA(
ID_RESERVA INT(11) PRIMARY KEY AUTO_INCREMENT,
ID_PELICULA INT(11) NOT NULL,
ID_CLIENTE INT(11) NOT NULL,
NUMERO_SALA INT(11) NOT NULL,
CODIGO_ASIENTO INT(11) NOT NULL,
FECHA_RESERVACION DATE NOT NULL,
HORA_RESERVACION TIME NOT NULL,
ESTADO_RESERVACION ENUM('Activa','Completada','Cancelada') NOT NULL,
FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
FOREIGN KEY(ID_PELICULA) REFERENCES PELICULA(ID_PELICULA)
ON UPDATE CASCADE 
ON DELETE RESTRICT
);

SET NAMES UTF8;


